name: train
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.2.2
  - dask=2021.10.0
  - matplotlib=3.5.3
  - pandas=1.2.5
  - lightgbm
  - scikit-learn=1.1.2
  - typer=0.6.1
  - shap
  - jupyter
  - ipykernel
  - pip:
      - mlflow==1.28.0
